# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [99]:
# Import your libraries:
import pandas as pd
import numpy as np
import warnings
from sklearn.model_selection import train_test_split as tts
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge, Lasso
from sklearn.linear_model import SGDRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.model_selection import cross_val_score as cvs
from sklearn.feature_selection import RFE
from sklearn.datasets import load_diabetes
from sklearn.svm import SVR
from sklearn import metrics

# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function.

In [31]:
# Your code here:
diabetes = load_diabetes()

Let's explore this variable by looking at the different attributes. Do this by looking at the `keys()` of this variable.

In [8]:
# Your code here:
diabetes.keys()

dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename', 'data_module'])

The next step is to read the description of the dataset. Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable

In [9]:
# Your code here:
print (diabetes.DESCR)

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, total serum cholesterol
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, total cholesterol / HDL
      - s5      ltg, possibly log of serum triglycerides level
      - s6      glu, blood sugar level

Note: Each of these 1

What are the variables in this dataset according to the description? List them in the markdown cell below

#### Enter your answer here:




Now explore the data. Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). In the cell below find the shape of the numpy array contained in the data portion of the diabetes variable.

In [17]:
# Your code here:
shape = diabetes.data.shape
shape

(442, 10)

In [35]:
df = pd.DataFrame(load_diabetes().data, columns=load_diabetes().feature_names)

In [37]:
df["target"] = load_diabetes().target

# Challenge 2 - Perform Supervised Learning on the Dataset

#### The data has already been split to predictor and response variables. The response variable is in the `target` portion of the variable. 

Given this information, let's apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset. In the cell below, import the linear regression class from sklearn. 

In [38]:
df.sample()

age       sex       bmi        bp        s1        s2        s3  \
90  0.012648 -0.044642 -0.025607 -0.040099 -0.030464 -0.045155  0.078093   

          s4        s5        s6  target  
90 -0.076395 -0.072128  0.011349    98.0

In [48]:
# Your code here:
lr = LinearRegression()

Initialize the model in the variable `diabetes_model`

In the cell below, fit the model and print the intercept and coefficients of the model. 

In [97]:
X = df.drop("target", axis=1)
y = df.target

SyntaxError: invalid character '“' (U+201C) (2746738043.py, line 1)

In [50]:
# Your code here:
X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.2)
res = X_train, X_test, y_train, y_test

In [51]:
diabetes_model = lr.fit(X_train, y_train)

In [54]:
coef = diabetes_model.coef_

In [55]:
coef

array([  19.44836011, -282.92508411,  482.56987894,  394.84355509,
       -536.01489114,  222.48595755,  -51.79406364,  210.42903385,
        626.89344957,   68.6887298 ])

In [56]:
intercept = diabetes_model.intercept_

In [60]:
print(f"The coefficients are {coef} and the intercept is {intercept}")

The coefficients are [  19.44836011 -282.92508411  482.56987894  394.84355509 -536.01489114
  222.48595755  -51.79406364  210.42903385  626.89344957   68.6887298 ] and the intercept is 153.36006295919054


# Bonus Challenge 1 - Conduct a Hypothesis Test on the Model

Once we have generated a linear model, we can test each coefficient using a t-test to see whether the confidence interval for the variable contains zero. We can also perform an overall F test to check whether at least one coefficient is significantly different from zero. 

Refer to the resource in this [link](https://onlinecourses.science.psu.edu/stat501/node/297/) for more details and perform the t-tests for the model above. Additionally, interpret the results and list coefficients are significantly different from zero.


Hint: use the statsmodels package.

Your result should look similar to this:

![ols](../ols-results.png)

In [63]:
# Your code here:
import statsmodels.formula.api as smf # regression modeling
diab = pd.DataFrame(load_diabetes().data, columns=load_diabetes().feature_names)
diab['target'] = diabetes.target
results = smf.ols("target ~ age + sex + bmi + bp + s1 + s2 + s3 + s4 + s5 + s6", data = diab).fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                 target   R-squared:                       0.518
Model:                            OLS   Adj. R-squared:                  0.507
Method:                 Least Squares   F-statistic:                     46.27
Date:                Thu, 18 Aug 2022   Prob (F-statistic):           3.83e-62
Time:                        15:53:25   Log-Likelihood:                -2386.0
No. Observations:                 442   AIC:                             4794.
Df Residuals:                     431   BIC:                             4839.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    152.1335      2.576     59.061      0.000     147.071     157.196
age          -10.0122     59.749     -0.168      0.867    -127.448     107.424
sex         -239.8191     61.222     -3.917      0.000    -360.151    -119.488
bmi          519.8398     66.534      7.813      0.000     389.069     650.610
bp           324.3904     65.422      4.958      0.000     195.805     452.976
s1          -792.1842    416.684     -1.901      0.058   -1611.169      26.801
s2           476.7458    339.035      1.406      0.160    -189.621    1143.113
s3           101.0446    212.533      0.475      0.635    -316.685     518.774
s4           177.0642    161.476      1.097      0.273    -140.313     494.442
s5           751.2793    171.902      4.370      0.000     413.409    1089.150
s6            67.6254     65.984      1.025      0.306     -62.065     197.316
==============================================================================
Omnibus:                        1.506   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.471   Jarque-Bera (JB):                1.404
Skew:                           0.017   Prob(JB):                        0.496
Kurtosis:                       2.726   Cond. No.                         227.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Challenge 2 - Peform Supervised Learning on a Pandas Dataframe

Now that we have looked at data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [64]:
# Your code here:

auto = pd.read_csv('../auto-mpg.csv')

Look at the first 5 rows using the `head()` function:

In [65]:
# Your code here:
auto.head()


mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [74]:
# Your code here:

What is the newest model year and the oldest model year?

In [86]:
# Your code here:
print(f'min : {auto.model_year.min()}')
print(f'max : {auto.model_year.max()}')

min : 70
max : 82


Check the dataset for missing values and remove all rows containing at least one missing value.

In [79]:
# Your code here:
auto.dropna(axis=0 , inplace =True)
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horse_power     0
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [80]:
# Your code here:
auto['cylinders'].value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

In [82]:
auto.sample()

mpg  cylinders  displacement  horse_power  weight  acceleration  \
314  26.4          4         140.0         88.0    2870          18.1   

     model_year  
314          80

In [81]:
auto.drop("car_name", axis=1, inplace=True)

In [83]:
# Your code here:
X = auto.drop("mpg", axis=1)
y = auto.mpg


In [84]:
# Your code here:
X_train, X_test, y_train, y_test = tts(X, y, test_size = 0.2)
res = X_train, X_test, y_train, y_test

Now we will the dataset that we processed and peform linear regression on this data to predict the mpg for each vehicle. Initialize the model in the cell below.

In [87]:
# Your code here:
auto_model = lr.fit(X_train, y_train)

Next, fit the model in the cell below.

In [93]:
# Your code here:
y_pred = auto_model.predict(X_test)
y_pred

array([13.95154676, 19.13104557, 25.9332906 , 22.22487361, 31.71052491,
       30.58451978, 33.21581416, 31.92139546,  9.35969673, 26.14068904,
        9.8161266 , 24.59716593, 12.92123313, 27.9772276 , 25.90414715,
       31.36950982, 21.25581366, 23.89800755, 23.61497286, 26.72295785,
       21.11896504,  8.2145701 , 20.00258216, 32.22715053, 30.22650084,
       29.51089917, 15.70940073, 17.4509555 , 21.48868791, 25.84854947,
       22.86221259, 19.68512621, 23.467409  ,  7.9974595 , 15.74613586,
       32.71039488, 30.65188538, 29.2924932 , 35.27346776, 11.7901276 ,
       27.68365882, 22.06874294, 27.33255633, 31.38350676, 25.74453274,
       32.76942404, 12.70751696, 27.25955375, 28.09665359, 15.10503194,
       28.59324722, 32.60755576, 23.31191804, 21.14573973, 16.85360112,
       15.04944364, 12.54734131, 24.3284736 , 30.08686155, 23.7905547 ,
       29.59048835, 29.49204918, 13.43901173, 10.99635494, 22.63360638,
       23.71415629, 18.61232273, 26.0565138 , 25.60623702, 26.39

# Challenge 3 - Evaluate the Model

the r squared score of a model tells us how much variation is explained by the model. In a typical dataset, most observations differ from the mean. When we create a model, we are trying to generate an equation that will tell us by how much each observation will differ from the mean. Obviously, the vast majority of models are not perfect. They can only predict some of the variation from the mean but not all of it. We attribute the rest of the difference between the actual value and the mean to random error. We would like random error to explain the as little as possible of the variation. This is why the r squared score is an important metric.

In the next cell, compute the r squared score of the model. Do this by first computing the predicted values and assign them to `y_pred`.

#### Our next step is to evaluate the model using the test data. We would like to ensure that our model is not overfitting the data. This means that our model will not be able to generalize well outside of the training data.

In the cell below, use the model to generate the predicted values for the training data and assign them to `y_test_pred`. Compute the r squared score for the test data by comparing the oberserved `y_test` data and the predicted `y_test_pred`.

In [98]:
# Your code here:
print(f"The R2 is: {metrics.r2_score(y_test, y_pred)} for the model")

The R2 is: 0.8141197302976594 for the model


# Challenge 4 - Improve the Model Fit

While the most common way to improve the fit of a model is by using regularization, there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [101]:
# Your code here:
X = auto.drop("mpg", axis=1)
y = auto.mpg
X_train09, X_test09, y_train09, y_test09 = tts(X, y, test_size = 0.1)
res = X_train09, X_test09, y_train09, y_test09
res

(     cylinders  displacement  horse_power  weight  acceleration  model_year
 353          4         105.0         74.0    2190          14.2          81
 270          4         134.0         95.0    2515          14.8          78
 220          4          85.0         70.0    1945          16.8          77
 369          4         112.0         88.0    2395          18.0          82
 68           8         350.0        155.0    4502          13.5          72
 ..         ...           ...          ...     ...           ...         ...
 307          6         173.0        115.0    2700          12.9          79
 251          8         302.0        139.0    3570          12.8          78
 241          6         146.0         97.0    2815          14.5          77
 151          4          79.0         67.0    2000          16.0          74
 164          6         231.0        110.0    3039          15.0          75
 
 [352 rows x 6 columns],
      cylinders  displacement  horse_power  weigh

Initialize a new model. Name this model `auto_model09`. Fit the model to the new sample data.

In [104]:
# Your code here:
auto_model09 = lr.fit(X_train09, y_train09)


Compute the predicted values and r squared score for our new model and new sample data.

In [105]:
# Your code here:
y_pred09 = auto_model.predict(X_test09)
y_pred09


array([25.12902021, 23.40515563, 23.2502762 , 25.73284125, 11.30029332,
       26.60840478, 24.97267515, 14.32527945, 17.38639465, 22.17596278,
       24.37504353, 25.65707327, 31.60765321, 16.11103666, 26.9896819 ,
        9.95142729, 33.49968956, 28.48161784, 11.58443988,  7.84183789,
        7.9661214 , 25.13491559, 28.67336413, 20.30977998, 33.37467948,
       30.97020734, 22.94206853, 24.61463659, 13.20730691, 18.96578003,
       27.37176871, 19.56797953, 30.66211511, 31.91578062, 31.04912925,
       23.93968932,  8.07115504, 27.5398145 , 22.59624111, 21.14340562])

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [106]:
# Your code here:
print(f"The R2 is: {metrics.r2_score(y_test09, y_pred09)} for the model")

The R2 is: 0.8272644043210097 for the model


# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [127]:
estimator = SVR(kernel="linear")

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [128]:
# Your code here:
selector = RFE(estimator, n_features_to_select=3, step=1)

Fit the model and print the ranking

In [129]:
# Your code here:
selector = selector.fit(X_test, y_test)


In [130]:
selector.ranking_

array([1, 3, 2, 4, 1, 1])

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [121]:
# Your code here:



array([1, 3, 2, 4, 1, 1])

Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [203]:
# Your code here: 

